apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
  labels:
    app: lab2-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: lab2-api